var data = [{
    "_count": "1",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "8916",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [2] but found [1]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}, {
    "_count": "2",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "7833",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [2] but found [1]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}, {
    "_count": "3",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "6116",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [2] but found [1]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}, {
    "_count": "4",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "10993",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [3] but found [2]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}, {
    "_count": "5",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "11010",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [3] but found [2]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}, {
    "_count": "6",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "11829",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [3] but found [2]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}, {
    "_count": "7",
    "_class": "com.groupon.local.clo.test.rest.external.ClaimDealIT",
    "_mothod": "testClaimingDeal",
    "_time": "17126",
    "_status": "FAILED",
    "_exception": "Error Explanation : Unexpected number of cards expected [4] but found [3]\u003cbr\u003e Class Name :  com.groupon.local.clo.test.rest.external.ClaimDealIT\u003cbr\u003e File Name :  ClaimDealIT.java\u003cbr\u003e Error Line Number :  44"
}];